trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.16

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py36, py37]
    os: linux
    pre_test:
    - bash: |
        mkdir /tmp/tmux
        cd /tmp/tmux
        curl --location --output tmux.zip https://github.com/asottile/babi/files/3666120/tmux.zip
        unzip tmux.zip
        echo '##vso[task.prependpath]/tmp/tmux/'
      displayName: upgrade tmux
